blueprint:
  name: Motion-activated Light - based on target
  description: Turn on a light when motion is detected and a targets tells you too.
  domain: automation
  source_url: https://github.com/sbu79/homeassistant/blob/master/light_on_motion_if_needed.yaml
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 120
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    condition_target:
      name: Light condition
      description: What entity tells you if lights should turn on?
      selector:
        target:
          entity:
            domain: input_boolean
            domain: input_select

# If motion is detected within the delay,
# we restart the script.
mode: restart
max_exceeded: silent

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "off"
  to: "on"

condition:
  - condition: state
    entity_id: !input condition_target
    state: 'on'

action:
  - service: light.turn_on
    target: !input light_target
  - wait_for_trigger:
      platform: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
  - delay: !input no_motion_wait
  - service: light.turn_off
    target: !input light_target
